# List

# Tuple

# Dict

In [9]:
#input_str = sys.stdin.read()
#import ast,sys
input_str = {'Name' : 'Monty' , 'Profession' : 'Singer' }
#input_dict = ast.literal_eval(input_str)
#ast.literal_eval(input_str)


#answer= input_str.get("Label","NA")

#try:
#    answer = input_dict['Label']#Type your answer here
#except:
#    answer="NA"


if "Label" in input_str:
    answer=input_str['Label']
else:
    answer="NA"
    
print(answer)

NA


In [12]:
list(input_str.keys()), list(input_str.values()), 

(['Name', 'Profession'], ['Monty', 'Singer'])

In [25]:
x=dict(a=1, b=2)

x.keys(), x.values()

(dict_keys(['a', 'b']), dict_values([1, 2]))

In [26]:
del x['a']

print (x)

{'b': 2}


In [22]:
x

{'b': 2}

# Sets

In [30]:
a=[1,2,3,4,5]
b=[44,55,67,34,23,5]
set1=set(a)
set2=set(b)
set1,set2

set1.difference(set2), set1.symmetric_difference(set2)

({1, 2, 3, 4}, {1, 2, 3, 4, 23, 34, 44, 55, 67})

In [33]:
input_list=[[1,2,3,4,5,6],[2,3,4,5,6,7,8,9]]
list_1 = input_list[0]
list_2 = input_list[1]

set_1 = set(list_1)#Type your answer here
set_2 = set(list_2)#Type your answer here
ans1= set_1.difference(set_2)
ans2= set_1.symmetric_difference(set_2)
answer_1 = list(ans1)#Type your answer here
answer_2 = list(ans2)#Type your answer here

print(answer_1)
print(answer_2)

[1]
[1, 7, 8, 9]


In [44]:
d = {0, 1, 2}
type(d)

for i in d:
    print ( d.add(i), end=" ")

None None None 

In [42]:
d.add(6)
d

{0, 1, 2, 6}

In [47]:
for i in range(1,6):
    if (i % 3 == 0):
        print(str(i) + " is Divisible by 3")
        break

    print(str(i) + " is not divisible by 3")

1 is not divisible by 3
2 is not divisible by 3
3 is Divisible by 3


In [49]:
for i in range(1,6):
    if (i % 3 == 0):
        print(str(i) + " is Divisible by 3")
        continue

    print(str(i) + " is not divisible by 3")

1 is not divisible by 3
2 is not divisible by 3
3 is Divisible by 3
4 is not divisible by 3
5 is not divisible by 3


In [50]:
for i in range(1,6):
    if (i % 3 == 0):
        print(str(i) + " is Divisible by 3")
        pass

    print(str(i) + " is not divisible by 3")

1 is not divisible by 3
2 is not divisible by 3
3 is Divisible by 3
3 is not divisible by 3
4 is not divisible by 3
5 is not divisible by 3


In [51]:
for i in range(1,6):
    if (i % 3 == 0):
        print(str(i) + " is Divisible by 3")
        

    print(str(i) + " is not divisible by 3")

1 is not divisible by 3
2 is not divisible by 3
3 is Divisible by 3
3 is not divisible by 3
4 is not divisible by 3
5 is not divisible by 3


In [62]:
input_str=['wood','old','apple','big','item','euphoria']

list_vowel = [word for word in input_str if word.lower()[:1] in ['a','e','i','o','u'] ]# [Type your answer here]
list_vowel

['old', 'apple', 'item', 'euphoria']

In [58]:
list_vowel1=  [word1 for word1 in list_vowel if word1.lower()[1] in ['a','e','i','o','u'] ]
list_vowel1

['euphoria']

In [60]:
input_str=['wood','old','apple','big','item','euphoria']

list_vowel = [word1 for word1 in [word for word in input_str if word.lower()[:1] in ['a','e','i','o','u'] ] \
              if word1.lower()[1] in ['a','e','i','o','u']]# [Type your answer here]
list_vowel

['euphoria']

In [82]:
n=4
dictionary= {i :  i*i for i in range(1,n+1) } #{Write your code here}
print(dictionary)

{1: 1, 2: 4, 3: 9, 4: 16}


In [77]:
n=4
dictionary={}
for i in range(1,n+1): #{Write your code here}
    dictionary[i] =  i*i 
print(dictionary)

{1: 1, 2: 4, 3: 9, 4: 16}


In [83]:
print([i+j for i in "abc" for j in "def"])

['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']


In [88]:
input_list=[5,6,4,8,9]
cube = list(map(lambda x: x*x*x, input_list))
print(cube)

[125, 216, 64, 512, 729]


In [ ]:
count = sum(list(map(lambda x: 1 if x[0]=="S" else 0, input_list)))

In [ ]:
first_name = input_list[0]
last_name = input_list[1]

name = list( map(lambda x,y: x+" "+y, first_name, last_name)) #Write your code here


In [92]:
import numpy as np
input_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
list_answer = np.array(input_list)[ list( map(lambda x: x%5==0 ,input_list) ) ] #Write your answer here
list_answer

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [94]:
f= lambda x,y: x**y
f(3,4)

81

# Lamdba Function

In [103]:
fac = lambda x: np.product([i for i in range(1,x+1) ])
fac(4)

24

# Map Function

In [114]:
Celsius = [39.2, 36.5, 37.3, 37.8]
Fahrenheit = map(lambda x: (float(9)/5)*x + 32, Celsius)

list(Fahrenheit)

[102.56, 97.7, 99.14, 100.03999999999999]

In [132]:
fib = [0,1,1,2,3,5,8,13,21,34,55]
result = map(lambda x: x % 2, fib)
list(result)

[0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1]

In [165]:
fib = lambda n: list( range(1,n))
n= list(fib(i) for i in range(2,6))
n
#fib = np.dot(fib,fib)
#fib(10)
#fib(10)

#result = filter(lambda x: x*x % 2, fib(10))
#list(result)

[[1], [1, 2], [1, 2, 3], [1, 2, 3, 4]]

In [120]:
num= list(range(1,10))

list(map(lambda x: x**2, num))

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [185]:
my_complex_fun = lambda x: round(np.cos( np.radians(x))**2,2)

n= list(range(0,100,10))

output=list(map(my_complex_fun, n))
output

[1.0, 0.97, 0.88, 0.75, 0.59, 0.41, 0.25, 0.12, 0.03, 0.0]

In [195]:
list(filter(lambda x: x%2!=1, output))

[0.97, 0.88, 0.75, 0.59, 0.41, 0.25, 0.12, 0.03, 0.0]

In [122]:
list( i**2 for i in range(1,10))

[1, 4, 9, 16, 25, 36, 49, 64, 81]

#### Element wise multiplication

In [197]:
l1=[1,2,3,4]
l2=[4,5,6,7]

list(map(lambda x,y: x*y, l1,l2))

[4, 10, 18, 28]

In [198]:
#Alternative way
a1= np.array(l1)
a2=np.array(l2)
a1*a2

array([ 4, 10, 18, 28])

# Filter Function

In [131]:
fib = [0,1,1,2,3,5,8,13,21,34,55]
result = filter(lambda x: x % 2, fib)
list(result)

[1, 1, 3, 5, 13, 21, 55]

In [174]:
import itertools
list(itertools.combinations( range(6),5))


[(0, 1, 2, 3, 4),
 (0, 1, 2, 3, 5),
 (0, 1, 2, 4, 5),
 (0, 1, 3, 4, 5),
 (0, 2, 3, 4, 5),
 (1, 2, 3, 4, 5)]

In [177]:
import functools
functools.reduce(lambda x,y: x+y, [47,11,42,13])

113

In [181]:
import functools
functools.reduce(lambda x,y: x*y, [1,2,3,4,5])

120

In [201]:
input_list= [[1,2,3],[4,5,6],[7,8,9]]
list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]

import numpy as np
array_1 = np.array([list_1, list_2, list_3],dtype=float)
array_1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [203]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [205]:
n=5
np.array( np.ones((n,n)))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [209]:
lines =[6,3,3]
int_x = int(lines[0])
rows_m = int(lines[1])
cols_n = int(lines[2])

np.ones( (rows_m,cols_n) ) *int_x

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [210]:
np.full( (5,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [241]:
n=3
r1=[[0,1],[1,0]]

ar=[]

for i in range(n):
    ar.append( np.tile( r1[i%2],n-2))
    

ar=np.array(ar)
ar

array([[0, 1],
       [1, 0],
       [0, 1]])

In [231]:
np.eye(6).ravel()

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1.])

In [232]:
ar.ravel()

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0])

In [251]:
arr=[0,1]*16

np.reshape(arr,(4,8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [260]:
n=4
arr=np.zeros( (n,n) )
for i in range(n):
    for j in range(n):
        if (i%2==0 and j%2!=0) or (i%2!=0 and j%2==0):
            arr[i,j]=1
            
arr
        

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [262]:
input_list=[[10,11,12,13],[15,12,13,14]]

list_1 = input_list[0]
list_2 = input_list[1]

import numpy as np
array_1 = np.array( (list_1, list_2) )#Type your answer here

print(array_1.shape)
print(array_1.ndim)

(2, 4)
2


In [263]:
array_1.itemsize

4

In [265]:
input_list=[[[1, 2], [5, 6]], [[3, 4], [7, 8]], [[9, 10, 11, 12]]]

list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]

# Import NumPy
import numpy as np
l1=np.array(list_1)
l2=np.array(list_2)
l3=np.array(list_3)

x=np.hstack( (l1,l2)) 
x=np.vstack( (x,l3) )
print (x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Numpy Vectorized Function

In [273]:
import random
a= np.random.randint(-20,20,10)

f = np.vectorize( lambda x: 1/(1+np.exp(-x)) )

a,f(a)

(array([ 18,  13,  12, -12,  19, -17, -20,   2,   9,  14]),
 array([9.99999985e-01, 9.99997740e-01, 9.99993856e-01, 6.14417460e-06,
        9.99999994e-01, 4.13993755e-08, 2.06115362e-09, 8.80797078e-01,
        9.99876605e-01, 9.99999168e-01]))

In [279]:
import random
a= np.random.randint(-20,20,16)

f = lambda x: 1/(1+np.exp(-x)) 

a,f(a)

(array([ 17, -13,  12, -18,  12, -20,  12,  12, -10,   7,  17,   0,   7,
         -5, -19, -18]),
 array([9.99999959e-01, 2.26032430e-06, 9.99993856e-01, 1.52299795e-08,
        9.99993856e-01, 2.06115362e-09, 9.99993856e-01, 9.99993856e-01,
        4.53978687e-05, 9.99088949e-01, 9.99999959e-01, 5.00000000e-01,
        9.99088949e-01, 6.69285092e-03, 5.60279641e-09, 1.52299795e-08]))

In [280]:
b=np.reshape(a, (4,4))
b

array([[ 17, -13,  12, -18],
       [ 12, -20,  12,  12],
       [-10,   7,  17,   0],
       [  7,  -5, -19, -18]])

In [281]:
np.linalg.inv(b)

array([[ 0.07363807, -0.06631183, -0.13688165, -0.11784596],
       [ 0.05197245, -0.09016907, -0.09830933, -0.11208516],
       [ 0.02191609, -0.00187852,  0.01878522, -0.02316844],
       [-0.00893342,  0.00124191, -0.04575245, -0.0457942 ]])

In [282]:
np.linalg.det(b)

95820.00000000007

In [283]:
np.linalg.eig(b)

(array([ 13.96436736+12.92745962j,  13.96436736-12.92745962j,
        -15.96436736 +3.12175738j, -15.96436736 -3.12175738j]),
 array([[-0.80372306+0.j        , -0.80372306-0.j        ,
         -0.38053312-0.0943409j , -0.38053312+0.0943409j ],
        [-0.2902617 +0.0415996j , -0.2902617 -0.0415996j ,
         -0.90825068+0.j        , -0.90825068-0.j        ],
        [-0.08203592-0.44528221j, -0.08203592+0.44528221j,
          0.0794277 -0.02109717j,  0.0794277 +0.02109717j],
        [ 0.01939795+0.25032867j,  0.01939795-0.25032867j,
         -0.00434176-0.12084012j, -0.00434176+0.12084012j]]))

In [284]:
np.linalg.eigvals(b)

array([ 13.96436736+12.92745962j,  13.96436736-12.92745962j,
       -15.96436736 +3.12175738j, -15.96436736 -3.12175738j])

In [290]:
c = b,
b,c

(array([[ 17, -13,  12, -18],
        [ 12, -20,  12,  12],
        [-10,   7,  17,   0],
        [  7,  -5, -19, -18]]), (array([[ 17, -13,  12, -18],
         [ 12, -20,  12,  12],
         [-10,   7,  17,   0],
         [  7,  -5, -19, -18]]),))

In [291]:
np.dot(b,c)

array([[[-113,  213,  594, -138]],

       [[ -72,  268, -120, -672]],

       [[-256,  109,  253,  264]],

       [[ 123,  -34,   43,  138]]])

In [295]:
input_list=[[1,2,3],[2,3,4],[4,2,6]]

list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]

import numpy as np
array_1 = np.array([list_1,list_2,list_3])
eigen = np.linalg.eigvals(array_1)#Type your answer here
inv = np.linalg.inv(array_1)#Type your answer here
det = np.linalg.det(array_1)#Type your answer here
print(eigen)
print(inv)
print(det)

#np.array([eigen, inv, det])

[ 9.62347538 -0.62347538  1.        ]
[[-1.66666667  1.          0.16666667]
 [-0.66666667  1.         -0.33333333]
 [ 1.33333333 -1.          0.16666667]]
-6.0


In [298]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
print(df.d)
print(df.columns)
print(df.shape)

Index(['X', 'Y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH',
       'wind', 'rain', 'area'],
      dtype='object')
(517, 13)


In [301]:
df.describe()

X           Y        FFMC         DMC          DC         ISI  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     4.669246    4.299807   90.644681  110.872340  547.940039    9.021663   
std      2.313778    1.229900    5.520111   64.046482  248.066192    4.559477   
min      1.000000    2.000000   18.700000    1.100000    7.900000    0.000000   
25%      3.000000    4.000000   90.200000   68.600000  437.700000    6.500000   
50%      4.000000    4.000000   91.600000  108.300000  664.200000    8.400000   
75%      7.000000    5.000000   92.900000  142.400000  713.900000   10.800000   
max      9.000000    9.000000   96.200000  291.300000  860.600000   56.100000   

             temp          RH        wind        rain         area  
count  517.000000  517.000000  517.000000  517.000000   517.000000  
mean    18.889168   44.288201    4.017602    0.021663    12.847292  
std      5.806625   16.317469    1.791653    0.295959    63.655818  
min      2.200000   15.000000    0.400000    0.000000     0.000000  
25%     15.500000   33.000000    2.700000    0.000000     0.000000  
50%     19.300000   42.000000    4.000000    0.000000     0.520000  
75%     22.800000   53.000000    4.900000    0.000000     6.570000  
max     33.300000  100.000000    9.400000    6.400000  1090.840000

In [302]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df.sort_values(['month','day'])#Type your code here to sort the dataset on month and day
print(df_2.head(20))

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
241  4  4   apr  fri  83.0   23.3   85.3   2.3  16.7  20   3.1   0.0   0.00
442  6  5   apr  mon  87.9   24.9   41.6   3.7  10.9  64   3.1   0.0   3.35
19   6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00
239  7  5   apr  sun  81.9    3.0    7.9   3.5  13.4  75   1.8   0.0   0.00
469  6  3   apr  sun  91.0   14.6   25.6  12.3  13.7  33   9.4   0.0  61.13
470  5  4   apr  sun  91.0   14.6   25.6  12.3  17.6  27   5.8   0.0   0.00
176  6  5   apr  thu  81.5    9.1   55.2   2.7   5.8  54   5.8   0.0   4.61
196  6  5   apr  thu  81.5    9.1   55.2   2.7   5.8  54   5.8   0.0  10.93
240  6  3   apr  wed  88.0   17.2   43.5   3.8  15.2  51   2.7   0.0   0.00
12   6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
78   1  2   aug  fri  90.1  108.0  529.8  12.5  14.7  66   2.7   0.0   0.00
142  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0   0.61
184  8  6   

In [306]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df[ ( (df.area>0) & (df.wind>1) & (df.temp>15) ) ] #Type your code here.
print(df_2.head(20))


     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
138  9  9   jul  tue  85.8   48.3  313.4   3.9  18.0  42   2.7   0.0  0.36
139  1  4   sep  tue  91.0  129.5  692.6   7.0  21.7  38   2.2   0.0  0.43
140  2  5   sep  mon  90.9  126.5  686.5   7.0  21.9  39   1.8   0.0  0.47
141  1  2   aug  wed  95.5   99.9  513.3  13.2  23.3  31   4.5   0.0  0.55
142  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0  0.61
143  1  2   jul  sat  90.0   51.3  296.3   8.7  16.6  53   5.4   0.0  0.71
144  2  5   aug  wed  95.5   99.9  513.3  13.2  23.8  32   5.4   0.0  0.77
145  6  5   aug  thu  95.2  131.7  578.8  10.4  27.4  22   4.0   0.0  0.90
147  8  3   sep  tue  84.4   73.4  671.9   3.2  24.2  28   3.6   0.0  0.96
148  2  2   aug  tue  94.8  108.3  647.1  17.0  17.4  43   6.7   0.0  1.07
149  8  6   sep  thu  93.7   80.9  685.2  17.9  23.7  25   4.5   0.0  1.12
150  6  5   jun  fri  92.5   56.4  433.3   7.1  23.2  39   5.4   0.0  1.19
151  9  9   jul  sun  90.

In [307]:
mylist1 = [True,  True,  True, False,  True]
mylist2 = [False, True, False,  True, False]
mylist1 and mylist2

[False, True, False, True, False]

In [309]:
mylist1 & mylist2

SyntaxError: invalid syntax (<ipython-input-309-0a043c9cea8e>, line 1)

In [310]:
np.array(mylist1) & np.array(mylist2)

array([False,  True, False, False, False])

In [311]:
True and 20 

20

In [312]:
False and 20

False

In [313]:
20 and []

[]

In [320]:
2 & 31

2

In [323]:
collection=[1,2,3]
len(collection) == 2

False

In [326]:
array1=[1,2,3]
print( bool([]), bool(array1) )

False True


In [341]:
mylist1 = [False, False, False,False,False]
mylist2 = [False, True, False,  True, False]
mylist1 and mylist2

[False, True, False, True, False]

In [343]:
mylist1 = [True, True, True,True,True]
mylist2 = [False, True, False,  True, False]
mylist1 and mylist2

[False, True, False, True, False]

In [344]:
bool(mylist1) , bool(mylist2)

(True, True)

In [345]:
import pandas as pd
df_1 = pd.read_csv('https://query.data.world/s/vv3snq28bp0TJq2ggCdxGOghEQKPZo')
df_2 = pd.read_csv('https://query.data.world/s/9wVKjNT0yiRc3YbVJaiI8a6HGl2d74')
df_3 = pd.merge(df_1, df_2,on="unique_id") #Type your code here.
print(df_3.head(20))

                           name                     address              city  \
0     arnie morton's of chicago   "435 s. la cienega blvd."     "los angeles"   
1                    art's deli       "12224 ventura blvd."     "studio city"   
2                 bel-air hotel      "701 stone canyon rd."         "bel air"   
3                    cafe bizou       "14016 ventura blvd."    "sherman oaks"   
4                     campanile       "624 s. la brea ave."     "los angeles"   
5               chinois on main             "2709 main st."    "santa monica"   
6                        citrus         "6703 melrose ave."     "los angeles"   
7           fenix at the argyle         "8358 sunset blvd."    "w. hollywood"   
8                       granita       "23725 w. malibu rd."          "malibu"   
9                    grill  the           "9560 dayton way"   "beverly hills"   
10                        katsu       "1972 hillhurst ave."       "los feliz"   
11                  l'orange

In [352]:
import pandas as pd
df_1 = pd.read_csv('https://query.data.world/s/vv3snq28bp0TJq2ggCdxGOghEQKPZo')
df_2 = pd.read_csv('https://query.data.world/s/9wVKjNT0yiRc3YbVJaiI8a6HGl2d74')
df_3 = pd.concat([df_1,df_2],) #Type your code here.
print(df_3.head())

                      address address_2             city city_2  \
0   "435 s. la cienega blvd."       NaN    "los angeles"    NaN   
1       "12224 ventura blvd."       NaN    "studio city"    NaN   
2      "701 stone canyon rd."       NaN        "bel air"    NaN   
3       "14016 ventura blvd."       NaN   "sherman oaks"    NaN   
4       "624 s. la brea ave."       NaN    "los angeles"    NaN   

            cuisine cuisine_2                       name name_2 unique_id  
0     "steakhouses"       NaN  arnie morton's of chicago    NaN       '0'  
1           "delis"       NaN                 art's deli    NaN       '1'  
2     "californian"       NaN              bel-air hotel    NaN       '2'  
3   "french bistro"       NaN                 cafe bizou    NaN       '3'  
4     "californian"       NaN                  campanile    NaN       '4'  


D:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  after removing the cwd from sys.path.


In [353]:
df_3

address             address_2             city  \
0     "435 s. la cienega blvd."                   NaN    "los angeles"   
1         "12224 ventura blvd."                   NaN    "studio city"   
2        "701 stone canyon rd."                   NaN        "bel air"   
3         "14016 ventura blvd."                   NaN   "sherman oaks"   
4         "624 s. la brea ave."                   NaN    "los angeles"   
..                          ...                   ...              ...   
747                         NaN       "3108 16th st."              NaN   
748                         NaN   "1870 fillmore st."              NaN   
749                         NaN         "8 sixth st."              NaN   
750                         NaN         "201 ivy st."              NaN   
751                         NaN       "2141 polk st."              NaN   

               city_2           cuisine      cuisine_2  \
0                 NaN     "steakhouses"            NaN   
1                 NaN           "delis"            NaN   
2                 NaN     "californian"            NaN   
3                 NaN   "french bistro"            NaN   
4                 NaN     "californian"            NaN   
..                ...               ...            ...   
747   "san francisco"               NaN       "french"   
748   "san francisco"               NaN     "american"   
749   "san francisco"               NaN   "vietnamese"   
750   "san francisco"               NaN        "pizza"   
751   "san francisco"               NaN      "mexican"   

                          name                         name_2 unique_id  
0    arnie morton's of chicago                            NaN       '0'  
1                   art's deli                            NaN       '1'  
2                bel-air hotel                            NaN       '2'  
3                   cafe bizou                            NaN       '3'  
4                    campanile                            NaN       '4'  
..                         ...                            ...       ...  
747                        NaN                        ti couz     '748'  
748                        NaN                      trio cafe     '749'  
749                        NaN                         tu lan     '750'  
750                        NaN                vicolo pizzeria     '751'  
751                        NaN  wa-ha-ka oaxaca mexican grill     '752'  

[864 rows x 9 columns]

In [351]:
df_3 = df_1.append(df_2)
df_3

D:\Users\admin\Anaconda3\lib\site-packages\pandas\core\frame.py:7138: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,


address             address_2             city  \
0     "435 s. la cienega blvd."                   NaN    "los angeles"   
1         "12224 ventura blvd."                   NaN    "studio city"   
2        "701 stone canyon rd."                   NaN        "bel air"   
3         "14016 ventura blvd."                   NaN   "sherman oaks"   
4         "624 s. la brea ave."                   NaN    "los angeles"   
..                          ...                   ...              ...   
747                         NaN       "3108 16th st."              NaN   
748                         NaN   "1870 fillmore st."              NaN   
749                         NaN         "8 sixth st."              NaN   
750                         NaN         "201 ivy st."              NaN   
751                         NaN       "2141 polk st."              NaN   

               city_2           cuisine      cuisine_2  \
0                 NaN     "steakhouses"            NaN   
1                 NaN           "delis"            NaN   
2                 NaN     "californian"            NaN   
3                 NaN   "french bistro"            NaN   
4                 NaN     "californian"            NaN   
..                ...               ...            ...   
747   "san francisco"               NaN       "french"   
748   "san francisco"               NaN     "american"   
749   "san francisco"               NaN   "vietnamese"   
750   "san francisco"               NaN        "pizza"   
751   "san francisco"               NaN      "mexican"   

                          name                         name_2 unique_id  
0    arnie morton's of chicago                            NaN       '0'  
1                   art's deli                            NaN       '1'  
2                bel-air hotel                            NaN       '2'  
3                   cafe bizou                            NaN       '3'  
4                    campanile                            NaN       '4'  
..                         ...                            ...       ...  
747                        NaN                        ti couz     '748'  
748                        NaN                      trio cafe     '749'  
749                        NaN                         tu lan     '750'  
750                        NaN                vicolo pizzeria     '751'  
751                        NaN  wa-ha-ka oaxaca mexican grill     '752'  

[864 rows x 9 columns]

In [350]:
df_2

name_2                  address_2  \
0        arnie morton's of chicago   "435 s. la cienega blv."   
1               art's delicatessen      "12224 ventura blvd."   
2                    hotel bel-air     "701 stone canyon rd."   
3                       cafe bizou      "14016 ventura blvd."   
4                        campanile      "624 s. la brea ave."   
..                             ...                        ...   
747                        ti couz            "3108 16th st."   
748                      trio cafe        "1870 fillmore st."   
749                         tu lan              "8 sixth st."   
750                vicolo pizzeria              "201 ivy st."   
751  wa-ha-ka oaxaca mexican grill            "2141 polk st."   

               city_2       cuisine_2 unique_id  
0       "los angeles"      "american"       '0'  
1       "studio city"      "american"       '1'  
2           "bel air"   "californian"       '2'  
3      "sherman oaks"        "french"       '3'  
4       "los angeles"      "american"       '4'  
..                ...             ...       ...  
747   "san francisco"        "french"     '748'  
748   "san francisco"      "american"     '749'  
749   "san francisco"    "vietnamese"     '750'  
750   "san francisco"         "pizza"     '751'  
751   "san francisco"       "mexican"     '752'  

[752 rows x 5 columns]

In [413]:
import numpy as np 
import pandas as pd

# Defining the three dataframes indicating the gold, silver, and bronze medal counts
# of different countries
gold = pd.DataFrame({'Country': ['USA', 'France', 'Russia'],
                         'Medals': [15, 13, 9]}
                    )
silver = pd.DataFrame({'Country': ['USA', 'Germany', 'Russia'],
                        'Medals': [29, 20, 16]}
                    )
bronze = pd.DataFrame({'Country': ['France', 'USA', 'UK'],
                        'Medals': [40, 28, 27]}
                    )

df=gold
df['Type']='gold'
df=df.append(silver)
df.loc[ df.Type.isna(),"Type"] = "silver"

df=df.append(bronze)
df.loc[ df.Type.isna(),"Type"] = "bronze"
df=df.groupby("Country").sum()#.sum(["Medals"])
#df=df.reset_index()

import warnings
warnings.filterwarnings("ignore")

df.sort_values(["Medals"],ascending=False, inplace=True)
df=df.astype( {"Medals":np.float16})


print (df)

         Medals
Country        
USA        72.0
France     53.0
UK         27.0
Russia     25.0
Germany    20.0


In [417]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
#Type your groupby command here
df_1 = df.groupby(["month","day"])#Type your code to find the mean of columns 'rain' and 'wind'
df_1 = df_1[['rain','wind']].mean()

print(df_1.head(20))

               rain      wind
month day                    
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000


In [416]:
df_1.mean()

X         Y       FFMC         DMC          DC       ISI  \
month day                                                                    
apr   fri  4.000000  4.000000  83.000000   23.300000   85.300000  2.300000   
      mon  6.000000  5.000000  87.900000   24.900000   41.600000  3.700000   
      sat  6.000000  4.000000  86.300000   27.400000   97.100000  5.100000   
      sun  6.000000  4.000000  87.966667   10.733333   19.700000  9.366667   
      thu  6.000000  5.000000  81.500000    9.100000   55.200000  2.700000   
...             ...       ...        ...         ...         ...       ...   
sep   sat  4.600000  4.320000  92.072000  116.148000  729.480000  8.596000   
      sun  3.629630  3.962963  90.062963  133.659259  736.318519  7.592593   
      thu  4.285714  4.095238  92.371429  121.652381  739.400000  9.528571   
      tue  4.684211  4.157895  90.036842  112.989474  718.136842  6.826316   
      wed  4.500000  4.500000  91.650000  123.964286  738.442857  8.507143   

                temp         RH      wind  rain       area  
month day                                                   
apr   fri  16.700000  20.000000  3.100000   0.0   0.000000  
      mon  10.900000  64.000000  3.100000   0.0   3.350000  
      sat   9.300000  44.000000  4.500000   0.0   0.000000  
      sun  14.900000  45.000000  5.666667   0.0  20.376667  
      thu   5.800000  54.000000  5.800000   0.0   7.770000  
...              ...        ...       ...   ...        ...  
sep   sat  21.524000  37.840000  3.460000   0.0  61.804400  
      sun  20.437037  48.000000  3.955556   0.0  14.010741  
      thu  20.390476  30.380952  3.357143   0.0   5.356190  
      tue  18.721053  43.736842  3.431579   0.0  26.352105  
      wed  20.407143  37.857143  3.378571   0.0  13.028571  

[64 rows x 11 columns]

In [419]:
df

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

      month  day
area  apr    fri     0.000000
             mon     3.350000
             sat     0.000000
             sun    20.376667
             thu     7.770000
                      ...    
rain  sep    sat     0.000000
             sun     0.000000
             thu     0.000000
             tue     0.000000
             wed     0.000000
Length: 128, dtype: float64

In [440]:
df

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

In [446]:
df_1.reset_index()

level_0 month  day         0
0      rain   apr  fri  0.000000
1      rain   apr  mon  0.000000
2      rain   apr  sat  0.000000
3      rain   apr  sun  0.000000
4      rain   apr  thu  0.000000
..      ...   ...  ...       ...
123    wind   sep  sat  3.460000
124    wind   sep  sun  3.955556
125    wind   sep  thu  3.357143
126    wind   sep  tue  3.431579
127    wind   sep  wed  3.378571

[128 rows x 4 columns]

In [442]:
import numpy as np
import pandas as pd
#df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_1 = pd.pivot_table (df, columns=['month', 'day'], aggfunc="mean", values=['rain','wind']) #Type your code here. 
print(df_1.head(20))

      month  day
rain  apr    fri    0.000000
             mon    0.000000
             sat    0.000000
             sun    0.000000
             thu    0.000000
             wed    0.000000
      aug    fri    0.066667
             mon    0.000000
             sat    0.000000
             sun    0.025000
             thu    0.000000
             tue    0.300000
             wed    0.000000
      dec    fri    0.000000
             mon    0.000000
             sun    0.000000
             thu    0.000000
             tue    0.000000
             wed    0.000000
      feb    fri    0.000000
dtype: float64


In [430]:
import numpy as np
import pandas as pd
#df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_1 = pd.pivot_table (df, columns=['month', 'day'], aggfunc="mean", values=['area']) #Type your code here. 
print(df_1.head(20))

      month  day
area  apr    fri     0.000000
             mon     3.350000
             sat     0.000000
             sun    20.376667
             thu     7.770000
             wed     0.000000
      aug    fri     5.600476
             mon     1.187333
             sat    14.054138
             sun     9.866500
             thu    32.198846
             tue     6.228571
             wed    13.950800
      dec    fri     9.270000
             mon    15.095000
             sun     8.980000
             thu     5.380000
             tue    24.770000
             wed    11.190000
      feb    fri     5.772000
dtype: float64


In [450]:
pd.pivot_table (df, index=['month', 'day'], aggfunc="mean", values=['area','wind'])

area      wind
month day                     
apr   fri   0.000000  3.100000
      mon   3.350000  3.100000
      sat   0.000000  4.500000
      sun  20.376667  5.666667
      thu   7.770000  5.800000
...              ...       ...
sep   sat  61.804400  3.460000
      sun  14.010741  3.955556
      thu   5.356190  3.357143
      tue  26.352105  3.431579
      wed  13.028571  3.378571

[64 rows x 2 columns]

In [459]:
import pandas as pd
#df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
print(round( 100*df.isna().sum(axis=0)/len(df) ,2))#Round off percentage values to 2 decimial places.

Ord_id                 0.00
Prod_id                0.00
Ship_id                0.00
Cust_id                0.00
Sales                  0.24
Discount               0.65
Order_Quantity         0.65
Profit                 0.65
Shipping_Cost          0.65
Product_Base_Margin    1.30
dtype: float64


In [472]:
df=df[df.isna().sum(axis=1)<=5]

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08   
...        ...      ...       ...        ...      ...       ...   
8385  Ord_1833   Prod_3  SHP_2527   Cust_637   611.16      0.04   
8386  Ord_2324   Prod_7  SHP_3189   Cust_851   121.87      0.07   
8387  Ord_2220   Prod_3  SHP_3019   Cust_851    41.06      0.04   
8388  Ord_4424   Prod_1  SHP_6165  Cust_1519   994.04      0.03   
8389  Ord_4444  Prod_13  SHP_6192  Cust_1519   159.41      0.00   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
0               23.0   -30.51           3.60                 0.56  
1               13.0     4.56           0.93                 0.54  
2               26.0  1148.90           2.50                 0.59  
3               43.0   729.34          14.30                 0.37  
4               35.0  1219.87          26.30                 0.38  
...              ...      ...            ...                  ...  
8385            46.0   100.22           4.98                 0.40  
8386            39.0    11.32           1.35                 0.40  
8387             4.0   -16.39           6.28                 0.35  
8388            10.0  -335.06          35.00                  NaN  
8389            44.0    34.68           0.98                 0.52  

[8379 rows x 10 columns]

In [477]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
df=df[df.isna().sum(axis=1)<=5]

print(round( 100*df.isna().sum(axis=0)/len(df) ,2)) #Round off to 2 decimal places.

Ord_id                 0.00
Prod_id                0.00
Ship_id                0.00
Cust_id                0.00
Sales                  0.00
Discount               0.42
Order_Quantity         0.42
Profit                 0.42
Shipping_Cost          0.42
Product_Base_Margin    1.06
dtype: float64


In [481]:
np.mean( df.Product_Base_Margin )

0.5124813027744285

In [482]:
df.loc[ df.Product_Base_Margin.isna(), 'Product_Base_Margin'] =np.mean( df.Product_Base_Margin )

In [483]:
import pandas as pd
#df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
#df=df[df.isna().sum(axis=1)<=5]

print(round( 100*df.isna().sum(axis=0)/len(df) ,2)) #Round off to 2 decimal places.

Ord_id                 0.00
Prod_id                0.00
Ship_id                0.00
Cust_id                0.00
Sales                  0.00
Discount               0.42
Order_Quantity         0.42
Profit                 0.42
Shipping_Cost          0.42
Product_Base_Margin    0.00
dtype: float64
