In [1]:
import numpy as np


In [47]:
a11 = np.array([[1,2],[5,6]])
b11 = np.array([[1,2],[12,9]])
a12 = np.array([3,7])
b21 = np.array([10,11])
b12 = np.array([3,5])
b22 = np.array([12])

print ("a11.b11")
print (a11.dot(b11))

print ("\na12.b21")
print (a12.dot(b21))

print ("\na11.b11+ a12.b21")
print (b11.T.dot(a11)+ b21.T.dot(a12))

a11.b11
[[25 20]
 [77 64]]

a12.b21
107

a11.b11+ a12.b21
[[168 181]
 [154 165]]


In [48]:
a11 = np.array([[1,2],[5,6]])
b11 = np.array([[1,2],[12,9]])
a12 = np.array([3,7])
b21 = np.array([10,11])
b12 = np.array([3,5])
b22 = np.array([12])

print ("a11.b11")
print (a11.dot(b11))

print ("\na12.b21")
print (a12.dot(b21))

print ("\na11.b11+ a12.b21")
print (b11.dot(a11)+ b21.dot(a12))

a11.b11
[[25 20]
 [77 64]]

a12.b21
107

a11.b11+ a12.b21
[[118 121]
 [164 185]]


In [49]:
a11 = np.array([[1,2],[5,6]])
b11 = np.array([[1,2],[12,9]])
a12 = np.array([3,7])
b21 = np.array([10,11])
b12 = np.array([3,5])
b22 = np.array([12])

print ("a11.b11")
print (a11.dot(b11))

print ("\na12.b21")
print (a12.dot(b21))

print ("\na11.b11+ a12.b21")
print (a11.dot(b11)+ a12.dot(b21))

a11.b11
[[25 20]
 [77 64]]

a12.b21
107

a11.b11+ a12.b21
[[132 127]
 [184 171]]


In [50]:
a11 = np.array([[1,2],[5,6]])
b11 = np.array([[1,2],[12,9]])
a12 = np.array([3,7])
b21 = np.array([10,11])
b12 = np.array([3,5])
b22 = np.array([12])

print ("a11.b11")
print (a11.dot(b11))

print ("\na12.b21")
print (a12.dot(b21))

print ("\na11.b11+ a12.b21")
print (a11.T.dot(b11)+ a12.T.dot(b21))

a11.b11
[[25 20]
 [77 64]]

a12.b21
107

a11.b11+ a12.b21
[[168 154]
 [181 165]]


In [51]:
print(a11.T)
print (a11)

[[1 5]
 [2 6]]
[[1 2]
 [5 6]]


$\vec{ a} \cdot \vec{ b} = |a|.|b|.cost(\theta) \frac{ \vec {a} } {\vec b} + \sigma b + \sum {\lower 0 \upper} 1 b$

In [70]:
import math
a=np.array([9,2])
b=np.array([-5,4])

a_on_b=np.dot(a,b)/np.linalg.norm(b)
b_on_a=np.dot(a,b)/np.linalg.norm(a)

print ((a_on_b/np.linalg.norm(b))*b)
print ((b_on_a/np.linalg.norm(a))*a)


[ 4.51219512 -3.6097561 ]
[-3.91764706 -0.87058824]


In [43]:
a11 = np.array([[1,2],[5,6]])
b11 = np.array([[1,2],[12,9]])
a12 = np.array([3,7])
b21 = np.array([10,11])
b12 = np.array([3,5])
b22 = np.array([12])

print ("a11*b11")
print (a11*b11)

print ("\na12*b21")
print (a12*b21)

print ("\na11*b11+ a12*b21")

print (a11*b11+ a12*b21)

a11*b11
[[ 1  4]
 [60 54]]

a12*b21
[30 77]

a11*b11+ a12*b21
[[ 31  81]
 [ 90 131]]


In [55]:
a=np.array([[1,2,3],[5,6,7],[9,12,13],[10,11,12]])
b= np.array([[1,2,3],[12,9,5],[10,11,12]])
a.dot(b)


array([[ 55,  53,  49],
       [147, 141, 129],
       [283, 269, 243],
       [262, 251, 229]])

In [32]:
a11.dot(b12)+a12.dot(b22)


ValueError: shapes (2,) and (1,) not aligned: 2 (dim 0) != 1 (dim 0)

In [18]:
a11.dot(b11)

array([[25, 20],
       [77, 64]])

In [20]:
a12.dot(b21)

107

array([[132, 127],
       [184, 171]])

In [ ]:
a= np.array( [[0,1],[1,1]] )

In [6]:
a

array([[0, 1],
       [1, 1]])

In [9]:
b=a*a

In [12]:
a

matrix([[0, 1],
        [1, 1]])

In [11]:
a=np.matrix(a)

In [13]:
a*a

matrix([[1, 1],
        [1, 2]])

In [14]:
a*a*a

matrix([[1, 2],
        [2, 3]])

In [15]:
a*a*a*a

matrix([[2, 3],
        [3, 5]])

In [19]:
a*a*a*a*a*a*a*a*a

matrix([[21, 34],
        [34, 55]])

## SVD

In [ ]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# SVD
U, s, VT = svd(A)
print(U)
print(s)
print(VT)

In [ ]:
# create m x n Sigma matrix
Sigma = np.zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = np.diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

In [1]:
from numpy import array
from sklearn.decomposition import TruncatedSVD
# define array
A = array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print(A)
# svd
svd = TruncatedSVD(n_components=2)
svd.fit(A)
result = svd.transform(A)
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]
